### ISSUE TITLE
Blockchain sync with Mongo

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-api#4]
Error when synching the blockchain to MongoDB

2018/08/20 19:05:11 helpers/GetJSON(): Error decoding JSON. json: cannot unmarshal number -2 into Go struct field Address.Balance of type uint

**Comment by girishramnani** [comment]
This is solvable by changing the Address to an `int` from `uint` but what I am concerned about is that why would there be a negative balance after all?

**Comment by girishramnani** [comment]
I have opened a PR @ruannelloyd https://github.com/Electra-project/electra-api/pull/5
