### ISSUE TITLE
Address API to to be completed

### ISSUE THREAD

**Issue by ruannelloyd** [Electra-project/electra-api#7]
/address/:hash 
/address/:hash/transactions

**Comment by girishramnani** [comment]
`/address/:hash/transactions` would require some work on the daemon as we are currently only storing address balances in the mongo.

**Comment by girishramnani** [comment]
and a clarification that `hash` is actually the `address` of kind `EauwWGA5pDpCf1DyEqV8WR8FuqoHnqR78a`

**Comment by girishramnani** [comment]
after a bit of research, I feel what we can do is that we can remove the `/address/:hash/transactions` and add the transactions in the `/address/:hash` itself.

**Comment by girishramnani** [comment]
Opened a PR to resolve this https://github.com/Electra-project/electra-api/pull/8
